### PR TITLE
Search functionality added

### PR DESCRIPTION
**Pull request by sainathadapa**
Two new functions:
- search_for_datasets
- get_datasets_from_a_catalog

This is related to the discussion in #14.

I still have some TODOs that I want to do. But I don't think there are any critical issues (I hope). I am open to suggestions or feature requests :)

### CODE REVIEW

**Comment by sainathadapa** [comment]
@steadyfish did you get a chance to take a look?

**Comment by steadyfish** [comment]
Hey @sainathadapa, 
Sorry for the delay, I will go over your chamges this weekend and get back to you.

**Comment by sainathadapa** [comment]
No worries. Just wanted to check.

**Comment by steadyfish** [comment]
@sainathadapa, your code looks good and I have now merged it with master. What additional todo's have you planned? I was wondering, having a vignette that utilises the search functionality and then goes on to download a dataset (using API and/or plain data download) would be great. 

Also, I have included you as package author since your contribution significantly improves the utility of this package. Hope you're ok with it.

**Comment by sainathadapa** [comment]
@steadyfish Thanks for merging the pull request and adding me as an additional author.

I have added some TODOs in the code itself. These lines start with `#TODO`. Here are the things that I  think are needed:
1. If a page download fails, retry once or twice.
2. I have used `<<-` global assignment operator. If you are going to submit the package to CRAN, this needs to be replaced, by using environments. `R CMD check` throws a warning whenever `<<-` is used.
3. Terms inputted by the user need to be escaped. For e.g. if the user runs `search_for_datasets('term1&term2')`, the `&` needs to be escaped.

Having a vignette is a good idea. I can write it, but I will not be able to get to it in the next one or two weeks. I can probably complete by the first week of June. 

BTW do you have plans to publish to CRAN?

**Comment by steadyfish** [comment]
Re: TODO 
1. I did face the 1st issue you mention above, could be helpful.
2. Yes, I want to publish it to CRAN eventually but haven't made any specific plans/timeline around it, so this should be ok for now. nice-to-have.
3. nice-to-have.

Re: Vignette 
- June should be OK I believe.

**Pull request merged**
