### PR TITLE
Vignette for Search functionality

### PR DESCRIPTION
**Pull request by sainathadapa**
I was finally able to get to this.

Changes in this pull request
1. New vignette
2. Bug fixes
3. Some argument names have changed
4. Switched the vignette template to prettydoc
5. Added a new function to download datasets

### CODE REVIEW

**Comment by sainathadapa** [comment]
@steadyfish hey can you review this PR?

**Comment by steadyfish** [comment]
Hey @sainathadapa, will review this in about a week.

**Comment by sainathadapa** [comment]
ok. thanks!

**Comment by sainathadapa** [comment]
@steadyfish Were you able to take a look at this?

**Pull request merged**
